### ISSUE TITLE
Clarification about model and results in paper

### ISSUE THREAD

**Issue by newalexander** [MilesZhao/PGCGM#3]
Hello and thanks for making this available! 

I have a few clarifying questions about what you have here vs. in the paper.

1. In your main table of results (Table 1, https://arxiv.org/pdf/2203.14352v2.pdf), you have a few different PGCGM versions (PGCGM, PGCGM+dist, PGCGM+dist+coord). Which of these configurations corresponds to the model you've uploaded here https://github.com/MilesZhao/PGCGM/blob/main/models/frac12/generator_weights.pth) ?
2. Can you clarify what filtering criteria you used to obtain the set of MP structures here (https://github.com/MilesZhao/PGCGM/blob/main/data/mpids.csv)?
3. Similarly, would it be possible for you to add OQMD and ICSD IDs for the other data you used?

Thanks!

**Comment by MilesZhao** [comment]
Hi Thanks for your interests in our work!

For your questions:
1. We used the model with the overall best performance (a.k.a., PGCGM+dist+coord) in this repo.
2. I wrote the steps below:

    - Ternary materials with only three base atom sites (a.k.a. one element is allowed to have only one base atom site);
    - Only keep materials that do not contain elements in Lanthanoid and Actinoid;
    - Ternary materials whose space group has more than 400 materials totally in three databases;
    - Ternary materials in OQMD whose fractional coordinates does not all belong to the set of {0.0, 0.25, 0.5, 0.75} since materials with fractional coordinates all falling in that set dominate the database.

4. I put all ids we used for training in [https://github.com/MilesZhao/PGCGM/blob/main/data/ids_for_mp_oqmd_icsd.csv](url). Please be noted that for materials in OQMD, the IDs start with "oqmd_" to tell them from materials in ICSD. Similar to materials in ICSD database.

**Comment by newalexander** [comment]
Hello @MilesZhao ! Congratulations on the publication of this work in npj Computational Materials. Would it be possible to add to this repo the scripts you used to preprocess the training data and train the generator and discriminator?

**Comment by MilesZhao** [comment]
Due to the university IP rights issue, we are not planning to release that part of the code.
