### ISSUE TITLE
Use git to download the 'datamodel.zip' in the colab tutorial

### ISSUE THREAD

**Issue by TheCutestCat** [MilesZhao/PGCGM#5]
hi, please consider using git to download the file, just like this:
$ git clone https://github.com/MilesZhao/PGCGM.git
$ mv /content/PGCGM/datamodel.zip /content
This is a little bit easier.
Thanks for your response.

**Comment by MilesZhao** [comment]
Some machines might not have git. If you want to run from your own machine, just git clone.
