### ISSUE TITLE
Number of final CIFs

### ISSUE THREAD

**Issue by onurboyar** [MilesZhao/PGCGM#6]
Hello,

Thank you for sharing your work!

I just run your code by setting number of samples to 1000 and I obtained 38 CIF files under ternary_final_cifs folder. How should I interpret these results? Does that mean the CIF conversion rate is 3.8%?

**Comment by MilesZhao** [comment]
That means only 38 CIF files can be recognized by pymatgen. In our work, we only focus on the CIF files recognized by pymatgen and then run DFT relaxation. For those dumped, after DFT relaxation, some of them might be valid too. But DFT relaxation is much more time consuming than pymagten readability verification.
